name: bwnp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  intl: ^0.20.2
  webview_flutter: ^4.13.0
  pull_to_refresh: ^2.0.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  another_flushbar: ^1.12.30
  shared_preferences: ^2.5.3
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  equatable: ^2.0.7
  sqflite: ^2.4.2
  rflutter_alert: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/